logging:
  level:
    springboot: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yun6?serverTimezone=GMT
    username: root
    password:
mybatis:
  # mapper-locations: mapper/*.xml
  type-aliases-package: springboot.pojo
